# Generated by Django 2.2.14 on 2020-07-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cliente', models.CharField(max_length=30)),
                ('arquivo', models.FileField(upload_to='arquivos')),
            ],
        ),
    ]
